### ISSUE TITLE
Dark Mode - User Card

### ISSUE THREAD

**Issue by josiiah** [Robotsrule4545/Interstellar-v2#1]
Hey, I just wanted to let you know that using Dark mode and toggling a profile card, the background is way too light!

- This applies to any modal / popup.

**Comment by josiiah** [comment]
![image](https://cdn.discordapp.com/attachments/981372246046163033/984864654750810142/unknown.png)

**Comment by josiiah** [comment]
This is also the case for any pop up modal

**Comment by Robotsrule4545** [comment]
ohno sorry
ill fix that

**Comment by Robotsrule4545** [comment]
I changed the color to a better one, thanks
